layout_spectrum: 0.6157888
typography_spectrum: 0.1093489
color:
  saturation: 0.5805364
  lightness: 0.6288992
  brandStrength: 0.5217665
  rhythmicContrast: 0.3633075
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: The Sheldons
